# Generated by Django 5.2.9 on 2026-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('average_flowrate', models.FloatField()),
                ('average_pressure', models.FloatField()),
                ('average_temperature', models.FloatField()),
                ('type_distribution', models.JSONField()),
            ],
        ),
    ]
